Feature/add readme
qoretechnologies/qorus-ui pull request #36
Opened 2023-01-11 07:27 UTC by rishabhmalik759

2023-01-11 07:34 UTC, Foxhoundn requested changes
Please change the logo to some kind of a gradient / shade of the Qorus purple instead of the green.

2023-01-11 07:34 UTC, Foxhoundn commented on CONTRIBUTING.MD
> +- 80 character line length
100

2023-01-11 07:34 UTC, Foxhoundn commented on CONTRIBUTING.MD
> +We use GitHub issues to track public bugs. Report a bug by opening a new issue on <code>github.com/qoretechnologies/{Repository-Name}/issues</code> it's that easy!
replace repository name with the name

2023-01-11 07:34 UTC, Foxhoundn commented on CONTRIBUTING.MD
> +3. If you've changed APIs, update the documentation.
There is no documentation for Qorus UI

2023-01-11 07:34 UTC, Foxhoundn commented on CONTRIBUTING.MD
> +5. Make sure your code lints.
No linters either

2023-01-11 07:34 UTC, Foxhoundn commented on SECURITY.md
> +Please do not open GitHub issues or pull requests - this makes the problem immediately visible to everyone, including malicious actors. Security issues in Qorus Integration Engine UI can be safely re
Does this email exist?

2023-01-11 07:34 UTC, Foxhoundn commented on README.md
> +This project exists thanks to all the people who contribute. [[Contribute](CONTRIBUTING.md)].
Remove this sentence from this repo.

2023-01-11 08:58 UTC, rishabhmalik759 commented on SECURITY.md
> +Please do not open GitHub issues or pull requests - this makes the problem immediately visible to everyone, including malicious actors. Security issues in Qorus Integration Engine UI can be safely re
no we can change it or make a new one

2023-01-18 10:27 UTC, Foxhoundn approved these changes

2023-01-18 10:28 UTC, Foxhoundn requested changes
Please increase the version in package.json

2023-02-08 13:13 UTC, Foxhoundn approved these changes

2023-02-08 13:14 UTC, merged